In [5]:
import glob
import pandas as pd
from datetime import datetime, timedelta

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from pandas.plotting import register_matplotlib_converters
from matplotlib.patches import Rectangle
from matplotlib.lines import Line2D
import matplotlib.patches as patches
import os
import numpy as np

%matplotlib auto
register_matplotlib_converters()

Using matplotlib backend: agg

# Check if the sleep times and the actigraph data align

In [6]:
destSleepPath = '/well/doherty/projects/raine/gen1_26/sleepLabelsClean/allSleepTime.csv'
sleepTimePath = '/well/doherty/projects/raine/gen1_26/sleepLabelsClean/sleepTime.csv'
sleepDf = pd.read_csv(sleepTimePath,  index_col=0)

In [7]:
data_dir = '/well/doherty/projects/raine/gen1_26/gt3x/wrist/sleepNov3/raw'
file_desp = data_dir + '/*.csv.gz'
epoch_files = glob.glob(file_desp)

In [4]:
sleepDf

      subject_id           start_time             end_time
0         830928  2017-04-17 22:29:14  2017-04-18 05:26:14
1         342948  2016-11-30 21:59:31  2016-12-01 05:06:01
2         343364  2016-05-26 22:05:51  2016-05-27 05:30:51
3         788310  2017-01-30 21:45:11  2017-01-31 06:20:41
4         906975  2015-10-29 22:23:09  2015-10-30 05:45:09
...          ...                  ...                  ...
996       183043  2016-11-08 21:56:31  2016-11-09 05:52:01
997       281230  2016-06-17 22:30:51  2016-06-18 06:09:21
998       163041  2017-02-08 22:14:55  2017-02-09 06:02:55
999       369218  2016-12-12 22:14:48  2016-12-13 06:01:18
1000      634032  2017-04-05 22:41:27  2017-04-06 06:36:57

[1001 rows x 3 columns]

In [8]:
def get_subjectID(file_path):
    path2file = file_path.split('/')[-1]
    path2file = path2file.split('_')[0]
    return path2file

In [9]:
epochTimeDf['subject_id'] = epochTimeDf['subject_id'].astype(int)

NameError: name 'epochTimeDf' is not defined

In [10]:
merged_df = sleepDf.join(epochTimeDf.set_index('subject_id'), on='subject_id')

In [11]:
merged_df.to_csv(destSleepPath)

In [13]:
merged_df

,subject_id,start_time,end_time,epoch_path,epoch_start_time,epoch_end_time
0,830928,2017-04-17 22:29:14,2017-04-18 05:26:14,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2017-04-17 18:00:00.033+0800 [Australia/Perth],2017-04-18 17:59:30.033+0800 [Australia/Perth]
1,342948,2016-11-30 21:59:31,2016-12-01 05:06:01,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2016-11-30 18:00:00.033+0800 [Australia/Perth],2016-12-01 17:59:30.033+0800 [Australia/Perth]
2,343364,2016-05-26 22:05:51,2016-05-27 05:30:51,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2016-05-26 18:00:00.033+0800 [Australia/Perth],2016-05-27 17:59:30.033+0800 [Australia/Perth]
3,788310,2017-01-30 21:45:11,2017-01-31 06:20:41,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2017-01-30 18:00:00.033+0800 [Australia/Perth],2017-01-31 17:59:30.033+0800 [Australia/Perth]
4,906975,2015-10-29 22:23:09,2015-10-30 05:45:09,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2015-10-29 18:00:00.033+0800 [Australia/Perth],2015-10-30 17:59:30.033+0800 [Australia/Perth]
...,...,...,...,...,...,...
996,183043,2016-11-08 21:56:31,2016-11-09 05:52:01,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2016-11-08 18:00:00.033+0800 [Australia/Perth],2016-11-09 17:59:30.033+0800 [Australia/Perth]
997,281230,2016-06-17 22:30:51,2016-06-18 06:09:21,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2016-06-17 18:00:00.033+0800 [Australia/Perth],2016-06-18 17:59:30.033+0800 [Australia/Perth]
998,163041,2017-02-08 22:14:55,2017-02-09 06:02:55,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2017-02-08 18:00:00.033+0800 [Australia/Perth],2017-02-09 17:59:30.033+0800 [Australia/Perth]
999,369218,2016-12-12 22:14:48,2016-12-13 06:01:18,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2016-12-12 18:00:00.033+0800 [Australia/Perth],2016-12-13 17:59:30.033+0800 [Australia/Perth]
1000,634032,2017-04-05 22:41:27,2017-04-06 06:36:57,/well/doherty/projects/raine/gen1_26/gt3x/wris...,2017-04-05 18:00:00.033+0800 [Australia/Perth],2017-04-06 17:59:30.033+0800 [Australia/Perth]

# Check if the times are within the range
The conditions are:
* the sleep labels occur at the same time or later than the actigraph time
* the sleep labels end at the same time or earlier than the actigraph time

In [43]:
yStartT = merged_df.iloc[0]['start_time']
yEndT = merged_df.iloc[0]['end_time']
xStartT = merged_df.iloc[0]['epoch_start_time']
xStartT = merged_df.iloc[0]['epoch_end_time']

In [44]:
yStartT

'2017-04-17 22:29:14'

In [45]:
xStartT

'2017-04-18 17:59:30.033+0800 [Australia/Perth]'

In [ ]:
first_day = datetime.datetime.strptime(file_date, '%d%m%Y')

# Merge data with labels

1. We first get a list of gt3x file names that we need to merge 
2. We find their sleep labels and merge them with x, together with their age info and subject_id 
3. For each merged DF with labels  plot the merge data and save it as an image 
4. Save the concatenated DFs into a single file

### 0. House keeping for file names. No need to run after if it is not the first time after parsing

In [7]:
# fix file names for having two recordings for the same subject at different dates 
# only the ones with postfix 1 have labels 
x_file_one =  os.path.join(data_dir, '563679_wrist_1.csv.gz')
x_file_two =  os.path.join(data_dir, '563679_wrist_2.csv.gz')
x_file_new =  os.path.join(data_dir, '563679_wrist_2016-04-01.csv.gz')
os.rename(x_file_one, x_file_new)
os.remove(x_file_two)


x_file_one =  os.path.join(data_dir, '953536_wrist_1.csv.gz')
x_file_two =  os.path.join(data_dir, '953536_wrist_2.csv.gz')
x_file_new =  os.path.join(data_dir, '953536_wrist_2016-04-01.csv.gz')
os.rename(x_file_one, x_file_new)
os.remove(x_file_two)

TypeError: rename() missing required argument 'dst' (pos 2)

### 1. get file names

In [10]:
root_dir = '/well/doherty/projects/raine/gen1_26/'
epoch_dir = os.path.join(root_dir, 'gt3x/wrist/sleepOct20/epoch')
raw_dir = os.path.join(root_dir, 'gt3x/wrist/sleepOct20/raw')
label_dir = os.path.join(root_dir, 'sleepLabelsClean')
image_dir = os.path.join(root_dir, 'imgs')
master_file_path = os.path.join(root_dir, 'gt3x/wrist/sleepOct20/master.csv.gz')
good_file_list = os.path.join(root_dir, 'gt3x/wrist/sleepNov3', 'good_file_list.csv')
file_desp = raw_dir + '/*csv.gz'
file_list = glob.glob(file_desp)

In [11]:
ok_file_list = pd.read_csv(good_file_list)
ok_file_list = ok_file_list['file_name']
ok_file_list = ok_file_list.apply(lambda x: get_subjectID(x))
ok_file_list = ok_file_list.astype(int)

In [12]:
LABEL_COLORS = {
    0: "#f95a5d",
    1: "#fda354",
    2: "#8c9d43",
    3: "#1c93b7",
    4: "#887ea5",
    5: "#3a3547"
}

def merge_rows(sleep_df, current_label):
    sleep_df = sleep_df[sleep_df['sleep_stage']==current_label]
    startTimes = []
    endTimes = []
    current_stage = []
    currentStartTime = None
    preTime = None
    labels = []

    for index, row in sleep_df.iterrows():
        currentTime = row['time']
        if preTime == None:
            currentStartTime = currentTime
        else:
            if currentTime - preTime > timedelta(seconds=30):
                startTimes.append(currentStartTime)
                endTimes.append(preTime+timedelta(seconds=30))
                currentStartTime = currentTime
                labels.append(current_label)
        preTime = currentTime


    startTimes.append(currentStartTime)
    endTimes.append(preTime+timedelta(seconds=30))        
    labels.append(current_label)
    
    stage_blocks = {
    'start_time': startTimes,
    'end_time': endTimes,
    'label': labels
    }
    stage_df = pd.DataFrame(stage_blocks)
    return stage_df

def parse_file_name(file_path):
    file_name = file_path.split('/')[-1]
    file_name = file_name[:-4] # remove .csv extension
    subjectID = file_name.split('_')[-1]
    file_date = file_name.split('_')[0]

    first_day = datetime.strptime(file_date, '%d%m%Y')

    if subjectID == '942099' or subjectID == '687006':
        # labels start on the same day:
        second_day = first_day
    else:
        second_day = first_day + timedelta(days=1)

    first_day_str = first_day.strftime('%d%m%Y')
    second_day_str = second_day.strftime('%d%m%Y')
    return first_day_str, second_day_str, subjectID

In [13]:
def xDate2yDate(xDate):
    year = xDate[:4]
    month = xDate[5:7]
    date = xDate[-2:]
    return date + month + year 

def xName2yName(x_name, label_root):
    full_file_name = x_name.split('/')[-1]
    full_file_name = full_file_name[:-7]
    subject_id = full_file_name.split('_')[0]
    date_str = full_file_name.split('_')[-1]
    yDate = xDate2yDate(date_str)
    
    return subject_id, os.path.join(label_root, yDate + '_' + subject_id + '.csv')

In [14]:
def updateTimes(first_day_str, second_day_str, x_df, y_df):
    current_date = first_day_str

    newtimes = []
    isSecondDay = False
    preHour = -1
    for index, row in y_df.iterrows():
        hour = int(row['time'].split(':')[0])
        if isSecondDay == False and ((hour < preHour and hour != 12) or (hour == 12 and preHour < hour)):
            isSecondDay = True 
            current_date = second_day_str
        row_time = datetime.strptime(current_date+' '+row['time'], '%d%m%Y %I:%M:%S %p') 
        newtimes.append(row_time)
        preHour = hour
    y_df['time'] = newtimes
    x_df['time']=x_df['time'].apply(lambda x: x[:-27])
    x_df['time']=x_df['time'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
    # y_df = y_df.join(x_df.set_index('time'), on='time')
    return x_df, y_df

In [15]:
def create_col(num_sample):
    cols = []
    for i in range(num_sample):
        cols.append('x'+str(i))
    for i in range(num_sample):
        cols.append('y'+str(i))
    for i in range(num_sample):
        cols.append('z'+str(i))
    return cols

In [21]:
def merge_xy(x_df, y_df, pid):
    features = []
    times = []
    sleep_stages = []
    num_samples = 2700
    mean_x = []
    mean_y = []
    mean_z = []
    
    for i in range(len(y_df)):
        startTime = y_df.iloc[i]['time']
        endTime = startTime+timedelta(seconds=30)
        current_df = x_df[(x_df['time'] >= startTime) & (x_df['time'] < endTime)]

        current_x = current_df['x'].tolist()
        current_y = current_df['y'].tolist()
        current_z = current_df['z'].tolist()
        xyz = np.concatenate((current_x, current_y, current_z), axis=None)
        if len(xyz) == num_samples:
            features.append(xyz)
            times.append(startTime)
            sleep_stages.append(y_df.iloc[i]['sleep_stage'])
            mean_x.append(np.mean(current_x))
            mean_y.append(np.mean(current_y))
            mean_z.append(np.mean(current_z))

        # else:
            # print(len(xyz))
            #print("skipping epoch")
    features = np.array(features)
    f_df = pd.DataFrame(features, columns=create_col(int(num_samples/3)))
    f_df['time'] = times
    f_df['sleep_stage'] = sleep_stages
    f_df['pid'] = pid
    f_df['mean_x'] = mean_x
    f_df['mean_y'] = mean_y
    f_df['mean_z'] = mean_z

    # good to compute average to make visu easier at a later time 
    
    return f_df

In [17]:
%matplotlib inline

In [19]:
file_list = ['/well/doherty/projects/raine/gen1_26/gt3x/wrist/sleepOct20/raw/942099_wrist_2015-06-15.csv.gz', 
            '/well/doherty/projects/raine/gen1_26/gt3x/wrist/sleepOct20/raw/687006_wrist_2015-05-12.csv.gz']

In [22]:
import traceback

files_with_NA = []
labels_with_NA = []
acc_without_labels = []
isPlotting = True
master_DF = None
i = 0

for x_file_path in file_list:
    i += 1
    if i % 10 == 0:
        print('Processing %d ' % i)
        
    subject_id, y_file_path = xName2yName(x_file_path, label_dir)
    image_save_path = os.path.join(image_dir, subject_id + 'raw.png')
    if int(subject_id) in ok_file_list is False:
        print("not in")
        print(subject_id)
        continue 
        
    try:
        # 2. We find their sleep labels and merge them with x, together with their age info and subject_id 
        if os.path.isfile(y_file_path) is False:
            acc_without_labels.append(y_file_path)
            continue

        x_df = pd.read_csv(x_file_path)
        y_df = pd.read_csv(y_file_path)
        if subject_id == '585573':
            # fix for strange file
            y_df = pd.read_csv(y_file_path, header=None)
            y_df.columns = ['idx', 'time', 'sleep_stage', '3']
            y_df = y_df[['idx', 'time', 'sleep_stage']]
        else:
            y_df.reset_index(inplace=True)
            y_df.columns = ['idx', 'time', 'sleep_stage']
        y_df = y_df[y_df.sleep_stage != 'NS']
        y_df = y_df.dropna()

        first_day_str, second_day_str, subjectID = parse_file_name(y_file_path) 

        # 2.2 we need to add time to the y labels 
        x_df, y_df = updateTimes(first_day_str, second_day_str, x_df, y_df)
        y_df = merge_xy(x_df, y_df, subject_id)

        if y_df.isnull().values.any():
            files_with_NA.append(x_file_path)
            labels_with_NA.append(y_file_path)

            
        x = y_df['time']
        y_df['sleep_stage'] = y_df['sleep_stage'] .astype(int)
        if i == 0:
            master_DF = y_df
        else:
            master_DF = pd.concat([master_DF, y_df])

        if isPlotting:
        
            # needs to change plotting for raw actigrahm
            # also change the visu for plotting 
            ## plotting
            fig,ax = plt.subplots(1,1,sharex=False, sharey=False, figsize=(18,12))
            ax.grid(True)
            ax.set_title('Participant = ' + str(subject_id), fontsize=16, fontweight='bold')                        
            #format x-axis                                                                  
            ax.xaxis.set_major_locator(mdates.HourLocator())                                 
            ax.xaxis.set_major_formatter(mdates.DateFormatter('%H'))
            ax.xaxis.set_minor_locator(mdates.HourLocator())                                
            ax.tick_params(axis='x', which='major', labelsize=20) 

            ax.tick_params(axis='y', which='major', labelsize=20)                           
            ax.set_ylabel('Mean acceleration (mg)', fontsize=24, fontweight='bold')
            #format plot area                                                               
            ax.spines['right'].set_visible(False)                                           
            ax.spines['top'].set_visible(False)                                             
            ax.xaxis.set_ticks_position('bottom')                                           
            ax.yaxis.set_ticks_position('left')    
            ytick_locs = [1.0, 0, -1, -1.25, -1.75, -2.25, -2.75, -3.25]
            ylabels = [1.0, 0, -1.0, 'awake', 'N1', 'N2', 'N3', 'REM']
            plt.yticks(ytick_locs, ylabels)
            ax.plot(x, y_df['mean_x'], color='black', label='x')
            ax.plot(x, y_df['mean_y'], color='yellow', label='y')
            ax.plot(x, y_df['mean_z'], color='blue', label='z')


            # OVERLAY LABELS
            legendPatches = []
            legendLabels = []
            label_height = 0.5
            label_y_start = -.5

            start = mdates.date2num(y_df['time'].min())
            end = mdates.date2num(y_df['time'].max())
            #ax.add_patch(Rectangle((start, -3.5), end-start, 2.5, color='grey', hatch='x'))
            
            label_locs = {
                0: -1.5,
                1: -2,
                2: -2.5,
                3: -3, 
                5: -3.5
            }
            label_name = {
                0: 'awake',
                1: 'N1',
                2: 'N2',
                3: 'N3', 
                5: 'REM'
            }
            for label in sorted(y_df['sleep_stage'].unique()):
                if label not in LABEL_COLORS.keys():
                    continue
                legendPatches += [patches.Patch(color=LABEL_COLORS[label], label=label)]
                legendLabels += [label_name[label]]

                stage_blocks_df = merge_rows(y_df, label)
                for ix, row in stage_blocks_df.iterrows():
                    start = mdates.date2num(pd.to_datetime(row['start_time']))
                    end = mdates.date2num(pd.to_datetime(row['end_time']))
                    duration = (row['end_time'] - row['start_time'])
                    if duration.total_seconds() < 10 * 3600: #make sure less than 10hrs
                        ax.add_patch(Rectangle((start, label_locs[label]), end-start, label_height, color=LABEL_COLORS[label]))
            # print legend
            # ax.legend(legendPatches, legendLabels, fontsize=24)
            plt.savefig(image_save_path)
            plt.show()
            plt.close()
    except Exception as e: 
        print(e)
        print(traceback.format_exc())
        print("File not working " + x_file_path)

[]
[]
Empty data passed with indices specified.
Traceback (most recent call last):
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1662, in create_block_manager_from_blocks
    make_block(values=blocks[0], placement=slice(0, len(axes[0])))
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 2722, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 131, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 1, placement implies 2700

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-22-0da6eba7c4b2>", line 45, in <module>
    y_df = merge_xy(x_df, y_df, subject_id)
  File "<ipython-input-21-a97181db0061>", line 33, in merge_xy
    f_df = pd.DataFrame(features, columns=create_col(int(num_samples/3)))
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 497, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 234, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1672, in create_block_manager_from_blocks
    raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
ValueError: Empty data passed with indices specified.

File not working /well/doherty/projects/raine/gen1_26/gt3x/wrist/sleepOct20/raw/942099_wrist_2015-06-15.csv.gz
[]
[]
Empty data passed with indices specified.
Traceback (most recent call last):
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1662, in create_block_manager_from_blocks
    make_block(values=blocks[0], placement=slice(0, len(axes[0])))
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 2722, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 131, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 1, placement implies 2700

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-22-0da6eba7c4b2>", line 45, in <module>
    y_df = merge_xy(x_df, y_df, subject_id)
  File "<ipython-input-21-a97181db0061>", line 33, in merge_xy
    f_df = pd.DataFrame(features, columns=create_col(int(num_samples/3)))
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 497, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 234, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/gpfs3/well/doherty/users/cxx579/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1672, in create_block_manager_from_blocks
    raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
ValueError: Empty data passed with indices specified.

File not working /well/doherty/projects/raine/gen1_26/gt3x/wrist/sleepOct20/raw/687006_wrist_2015-05-12.csv.gz

In [ ]:
master_DF

In [ ]:
master_DF.to_csv(master_file_path, compression='infer')

In [ ]:
## Acc without labels
print(len(acc_without_labels))
acc_without_labels

In [4]:
# write html file in plots dir to visualise all plots
image_dir = '/well/doherty/projects/raine/gen1_26/imgs/'


html = '<html><head><title>Annotation plots</title></head><body>'
viz_fileList = sorted([e for e in os.listdir(image_dir) if e.endswith('.png')])
for viz in viz_fileList:
    html += '<img src="' + viz + '" width=1400 height=500><br>'
html += '</body></html>'
w = open(image_dir + 'viz.html','w')
w.write(html)
w.close()

In [65]:
master_DF

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,z896,z897,z898,z899,time,sleep_stage,pid,mean_x,mean_y,mean_z
0,0.444,0.444,0.435,0.435,0.441,0.441,0.444,0.441,0.441,0.435,...,-0.278,-0.278,-0.281,-0.278,2017-01-24 22:05:04,0,490916,0.441659,0.852343,-0.282316
1,0.444,0.446,0.444,0.441,0.441,0.444,0.446,0.446,0.446,0.444,...,-0.222,-0.225,-0.225,-0.222,2017-01-24 22:05:34,0,490916,0.426099,0.865066,-0.262344
2,0.414,0.408,0.414,0.417,0.408,0.405,0.408,0.414,0.414,0.417,...,-0.225,-0.228,-0.228,-0.225,2017-01-24 22:06:04,0,490916,0.413088,0.881839,-0.227632
3,0.414,0.408,0.408,0.414,0.414,0.414,0.417,0.414,0.417,0.408,...,-0.228,-0.234,-0.225,-0.225,2017-01-24 22:06:34,0,490916,0.411267,0.882569,-0.227028
4,0.417,0.417,0.417,0.414,0.414,0.408,0.414,0.414,0.417,0.420,...,-0.222,-0.225,-0.225,-0.225,2017-01-24 22:07:04,0,490916,0.416530,0.880821,-0.224326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,0.998,0.998,0.998,0.998,0.998,0.992,0.989,0.998,1.001,1.001,...,-0.035,-0.032,-0.035,-0.035,2015-06-23 05:48:19,0,639521,0.999302,0.037997,0.018639
938,0.767,0.767,0.776,0.770,0.770,0.764,0.770,0.770,0.764,0.770,...,-0.605,-0.611,-0.611,-0.605,2015-06-23 05:51:49,1,639521,0.784656,-0.018172,-0.619787
939,0.793,0.793,0.793,0.793,0.793,0.793,0.793,0.793,0.791,0.791,...,-0.944,-0.938,-0.944,-0.938,2015-06-23 05:52:19,0,639521,0.308237,0.149522,-0.369434
940,0.106,0.109,0.098,0.092,0.095,0.106,0.103,0.098,0.098,0.106,...,0.044,0.027,0.009,-0.023,2015-06-23 05:52:49,0,639521,0.503357,-0.115651,-0.356520
941,1.018,1.015,0.983,0.960,1.062,1.059,0.971,0.998,1.012,1.012,...,0.009,0.012,0.009,0.012,2015-06-23 05:53:19,0,639521,0.753404,-0.384138,-0.222873